# Chainlink CRE project for Hourglass
staging-settings:
  rpcs:
    - chain-name: monad-testnet
      url: ${MONAD_TESTNET_RPC}
production-settings:
  rpcs:
    - chain-name: monad-testnet
      url: ${MONAD_TESTNET_RPC}
