// Exports Foundry ABIs to typed TS consts for the web app.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
const out = "web/lib/generated";
mkdirSync(out, { recursive: true });
let src = "// generated by scripts/export-abi.mjs — do not edit\n";
for (const [name, file] of [["hourglassAbi", "Hourglass.sol/Hourglass.json"], ["hourTokenAbi", "ComputeHourToken.sol/ComputeHourToken.json"], ["mockUsdcAbi", "MockUSDC.sol/MockUSDC.json"]]) {
  const { abi } = JSON.parse(readFileSync(`contracts/out/${file}`, "utf8"));
  src += `export const ${name} = ${JSON.stringify(abi, null, 2)} as const;\n\n`;
}
writeFileSync(`${out}/abis.ts`, src);
console.log("wrote", `${out}/abis.ts`);
